### ISSUE TITLE
Resource leak in nft_queue if queue is not empty at nft_shutdown time

### ISSUE THREAD

**Issue by mikedoug** [seanpburke/Nifty#1]
I'm not sure if this is still being maintained, but I have some code that was using an older version of nft_queue and wanted to try upgrading to this version since you've now built in the reference counting (thank you!).

However, after converting to this new version, I have determined with 100% certainty that there is a resource leak if this condition happens:

1. You call `nft_queue_shutdown(q, 0)` when there is an item waiting in the queue.
2. You then immediately call `nft_queue_pop_wait(q,0)` on the queue until it is drained (returns NULL).  I believe this is what the documentation says you need to do in order to get the queue to shut down.

I see exactly why this is happening -- in the `nft_queue_shutdown(...)` code you release the original creation reference count if and only if the queue is empty.  What you don't do upon popping items from the queue and the queue becoming empty to see if it is in shutdown and also releasing the extra count.

I have a fix for this which I'll push up to github momentarily and open a pull request.

**Comment by seanpburke** [comment]
Thanks very much for finding this bug, and for submitting a pull request. Much appreciated!

**Comment by mikedoug** [comment]
Very welcome!  Thanks for including it into the code base!
